//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiShowroom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDetail()
        {
            this.Bookings = new HashSet<Booking>();
        }
        [Required]
        public int CarID { get; set; }
        [Required]
        public string CarName { get; set; }
        [Required]
        public Nullable<decimal> CarPrice { get; set; }
        [Required]
        public Nullable<int> BranchID { get; set; }
     

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Required]
        public virtual ICollection<Booking> Bookings { get; set; }
        [Required]
        public virtual BranchDetail BranchDetail { get; set; }
    }
}
